### PR TITLE
Add cross-language testing to Python pipeline

### PR DESCRIPTION
**Pull request by petrovicboban**

### CODE REVIEW

**Comment by petrovicboban** [comment]
@edwardwliu @theo-s can you provide feedback on this PR? It's not finished yet. I'm missing import of `Rforestry` R lib in `R_test.R`, need to make sure it's importable from there, but don't know really how to do it if only source R package is available.
This test will run as part of python pipeline, but I need to implement it in R pipeline too, for cases when only R source is changed.

**Comment by edwardwliu** [comment]
Hi @petrovicboban, this is basically aligned with what I had in mind. Writing to stdout is a reasonable first step, maybe we'll converge on another standardized format in a future PR. 

As for the Rforestry import, would this same issue exist if we ran it from the R pipeline? Potentially we could build the source as an earlier step in the pipeline.

**Comment by edwardwliu** [comment]
We could build the current R source on master. Alternatively, I think it makes sense to create a tag indicating the currently release CRAN version of R. This would just be manually updated whenever we manually release to CRAN. The Python pipeline would then build the specific released version, while the R pipeline could build its own branch.

**Comment by petrovicboban** [comment]
For cases where you add new functionality in C++ and change R/Python wrappers, or cases where you just change C++, we would need to build Python/R packages from PR branch and compare results, so we can't pull already built packages from public repos.

**Comment by edwardwliu** [comment]
I'm good with building the R/Python packages from the PR branch, especially in the case of C++ changes.

**Comment by petrovicboban** [comment]
@edwardwliu python pipeline can now run cross-language tests (it's on developers to add appropriate tests) during test phase of linux builds. We are missing the same while building macos packages, but we can live without them for now.

Also, I would like to create new PR for adding the same tests during R pipeline execution.

**Comment by petrovicboban** [comment]
It's important to say that R package is built and tests are run using `R 4.0.0`

**Comment by edwardwliu** [comment]
LGTM thanks Boban. Why is building the macOS package different in this use case? Running the same tests during R pipeline execution makes sense as a next step.

**Review by edwardwliu — APPROVED** [review]

**Pull request merged**
