### PR TITLE
Custom sampling

### PR DESCRIPTION
**Pull request by theo-s**
Making this a PR so that we can review changes + comment on this easily

### CODE REVIEW

**Comment by theo-s** [comment]
An update on this, I have gone through the R + C++ code for this implementation and think that this version both builds trees on the correct observations from the training data, and has the desired performance when these trees are later used for prediction with `aggregation = "oob"` and `aggregation = "doubleOOB"`. 

I have done some initial tests for this as well as sampling outside of the forest and training with the sampled indices. It would be good to test both the training and prediction further as well as the interaction with other features as well as make sure the documentation is very precise and easy to understand.

**Comment by JasjeetSekhon** [comment]
What if aggregation is just OOB (which is what we are currently mostly
using)?  (doubleOOB drops a disturbing amount of data when used with the
groups option, as we have discussed before).

**Comment by edwardwliu** [comment]
Thanks for collaborating on this Theo. @JasjeetSekhon if an observation appears in the provided "excluded" set of a tree, the tree will not be used for out-of-bag predictions. That is, `aggregation = oob` means an observation should not be in averaging or excluded, and `aggregation = doubleOOB` should not be in splitting, averaging, or excluded.

**Comment by theo-s** [comment]
Thanks for following up on this Edward, this is also my understanding of what we are doing right now. 

So explicitly, when we have a tree and are predicting for new data, when aggregation is set to "oob" we predict with the tree for all observations in `setDiff(1:n, Union(averagingIndices, excludedIndices))` and when  aggregation is set to "doubleOOB" we predict with the tree for all observations in `setDiff(1:n, Union(splittingIndices, averagingIndices, excludedIndices))

**Comment by theo-s** [comment]
Another thing that has to be done still. Do we always require the user to specify `customExcludedSample`, and if we do, do we require it for every tree?

**Comment by edwardwliu** [comment]
@theo-s For now, I think customExcludedSample` should be optional. The user doesn't have to provide the parameter and it doesn't have to be set for every tree when given.

**Comment by theo-s** [comment]
@edwardwliu that sounds good. The above commit should change this to be optional and also allow the user to specify excluded indices for some but not all of the trees that are given `customSplittingSample`/`customAveragingSample` parameters. 

For now the way I have implemented this is that if `customSplittingSample` is of length `n` and `customExcludedSample` is of length `K` the excluded samples will apply to the first `K` trees of the forest (the trees grown with splitting samples from the first `K` entries of `customSplittingSample`

**Comment by theo-s** [comment]
One thing to note, in order to make the predictions exact, we currently order the trees in the C++ forest (and also the R forest when we save/load trees since this just pulls them in the same order as they are in C++) based on descending seed values. When growing the `i`th tree in the forest with a given seed `s`, it is given the seed `i*s`, meaning the trees are stored in the reverse order that they are trained. 

This is why in the tests we compare the `i`th entry of `customSplittingSample` to the `splittingSampleIndex` of the `ntree+1-i`th tree. It is kind of confusing this way and we should probably reverse the order that we store the trees in, but then that will change the results of many of our high precision tests that assume this ordering of the trees.

**Comment by theo-s** [comment]
An update from my end, I have looked through the C++ code for prediction with different aggregations when we have groupSampling and also tested this pretty heavily in the code. 

In addition to this, I have added some advanced tests for the interaction of custom sampling with important features, including: the interaction of `customSampling` and `monotonicity`,`customSampling` and `monotonicity` + `monotoneAvg`, as well as with `groups` with `aggregation="oob"` and `aggregation="doubleOOB"` and `groups` with `aggregation="oob"` and `aggregation="doubleOOB"` and `monotonicity`/ `monotoneAvg`. To check out the test file itself (which has been added to the `testthat` test suite, see [here](https://github.com/forestry-labs/Rforestry/blob/custom-sampling/R/tests/testthat/test-advancedCustomSampling.R).

From all of these tests, I believe the current implementation of custom sampling is working as intended when combined with the above features. 

One thing I have added is an error for the case when the user gives customSamples as well as `groups`, and the custom samples for the averaging/splitting/excluded sets don't contain disjoint groups. I have added an error to check for this case though. @edwardwliu after our talk earlier today, this is another part of the preprocessing you should check out. See [here](https://github.com/forestry-labs/Rforestry/blob/62eff60aae31e006ffc9d47c7e439077e11037a9/R/R/forestry.R#L286) for the exact code.

**Comment by theo-s** [comment]
P.S. in addition to being a useful feature, custom sampling actually makes debugging/writing efficient tests for many corner cases a lot more efficient now.

**Review by edwardwliu — APPROVED** [review]
Hi @theo-s, ran through some downstream usage. Could review the final state of the code again, but we're good to merge.

**Pull request merged**
