### PR TITLE
Remove b2 tag from Python versioning

### PR DESCRIPTION
**Pull request by edwardwliu**
Updates PyPI release to include: 
- exact reproducibility with R version
- fix for groups
- observation weights without groups

### CODE REVIEW

**Comment by theo-s** [comment]
This looks good, merging into master. Do I need to do anything further for the Python release to push to PyPI?

**Comment by edwardwliu** [comment]
IIUC this should've released to PyPI via this [pipeline](https://github.com/forestry-labs/Rforestry/blob/d9006ff4f1055964c41c5d7cc941460945f51322/.github/workflows/python.yaml#L199). @petrovicboban to confirm.

**Comment by theo-s** [comment]
Thanks! I thought so as well, examining the GIthub actions, it seems like the last step (the upload), was skipped (see [here](https://github.com/forestry-labs/Rforestry/actions/runs/4846028068/jobs/8635436257)), so not sure if I have to do something else to trigger this.

**Comment by petrovicboban** [comment]
Merging PRs to master will not trigger release. What it does is pushing tags.
So once you merge all PRs you want to master, create appropriate tag (needs to match regex) and push it, and that will create github release, and upload package to pypi.
We should match tag with version string in pyproject.toml, but there is no constraint on that yet.

**Comment by theo-s** [comment]
Thanks for the explanation, this makes sense.

**Pull request merged**
