### PR TITLE
Remove groups_mapping parameter

### PR DESCRIPTION
**Pull request by edwardwliu**
Only uses single Panda series to represent groups and removes groups from initial forest instantiation. Fixes the implementation of groups with reproducibility against the R package. Also resolves tree representation of averaging info.

### CODE REVIEW

**Comment by petrovicboban** [comment]
I would rebase this and set last commit "update styling" as fixup for previous one, so we don't have small style fix commits.

**Review by theo-s — APPROVED** [review]
This looks good to me, we should merge into master after Boban's comment is addressed

**Comment by edwardwliu** [comment]
FYI ended up with odd history, but will keep squashing style checks in mind going forward.

**Comment by theo-s** [comment]
Sounds good, thanks for removing this

**Pull request merged**
