### PR TITLE
Test upstream merge resolutions to be merged into fork

### PR DESCRIPTION
**Pull request by edwardwliu**
Pull request https://github.com/forestry-labs/Rforestry/pull/54 was created to merge the Python fork master branch into the main repo's master branch.
 
This is a draft PR to test resolved merge conflicts in https://github.com/theo-s/Rforestry/pull/22 prior to merging to the fork's master branch.

### CODE REVIEW

**Comment by petrovicboban** [comment]
@theo-s  it's easier to resolve these conflicts, if we create branch `target` in forestry-labs, and then create PR from your `master` to `target`. Then we can push changes to `target` until we resole all conflicts.

**Comment by edwardwliu** [comment]
@petrovicboban Are you able to create the `target` branch and help with resolving conflicts?

**Comment by petrovicboban** [comment]
Yes I am, but I need help with conflicts resolving (mostly C++ code and some of R tests)

**Comment by edwardwliu** [comment]
Sounds good, I'll close out this PR. You can move forward and tag Theo if you run into blockers with any specific conflicts.

**Pull request closed without merging**
