### PR TITLE
reconstructTrees parallelization resolves #25

### LINKED ISSUE #25: [Runtime ] relinkCPP_ptr
In some cases, it appears that the runtime of relinkCPP_ptr is scaling nonlinearly in the number of trees in the forest.

### PR DESCRIPTION
**Pull request by linanqiu**
Use the same parallelization pattern elsewhere in forestry.cpp for `reconstructTrees` resolves #25

### CODE REVIEW

**Comment by theo-s** [comment]
Do we need to add, after reconstructing the tree and before saving it to forest:
            #if DOPARELLEL
            std::lock_guard<std::mutex> lock(threadLock);
            #endif

**Comment by linanqiu** [comment]
@theo-s yup you're right added that

**Comment by JasjeetSekhon** [comment]
Need to copy the sort from:

https://github.com/forestry-labs/Rforestry/blob/5e4d8d17112d5cdf49e01b0e945a6dfbd7806e2a/src/forestry.cpp#L124

**Comment by theo-s** [comment]
In order to pass the high precision tests for checking that the  forest is the same after loading, we need the trees to be stored in the same order as they were during training. We do this with parallel training by sorting the trees by random seed after training is done. 

Outside the loop over tree id's, once all have been reconstructed, we should add the code to sort by seed
`
// Try sorting the forest by seed, this way we should do predict in the same order
  std::vector< std::unique_ptr< forestryTree > >* curr_forest;
  curr_forest = this->getForest();
  std::sort(curr_forest->begin(), curr_forest->end(), [](const std::unique_ptr< forestryTree >& a,
                                                         const std::unique_ptr< forestryTree >& b) {
    return a.get()->getSeed() > b.get()->getSeed();
  });
`

**Comment by linanqiu** [comment]
@theo-s do we want to do this only in the parallel case or in the serial case as well? Because it didn't exist in the serial case. Either way I'll just add it outside the DOPARELLEL if

**Comment by theo-s** [comment]
We should do it outside

**Review by JasjeetSekhon — APPROVED** [review]
Looks good now.

**Pull request merged**
