### PR TITLE
Sync fork

### PR DESCRIPTION
**Pull request by petrovicboban**

### CODE REVIEW

**Comment by petrovicboban** [comment]
@edwardwliu @theo-s this is mergable now.

**Comment by edwardwliu** [comment]
Great thanks @petrovicboban! @theo-s When you get the chance, could you take a closer look at the changes both code and structural we're introducing to the `forestry-labs:master` branch?

**Comment by theo-s** [comment]
Thanks for opening the PR, I will take a closer look at the changes and get back

**Comment by theo-s** [comment]
I have taken a look at the overall file structure of branch as well as the parameters we have included in this version etc. Aside from the above changes, there is nothing I see that should give us pause to merge this in. Once it is merged in, then we should start testing the two packages against each other, I am sure there are some places where performance will diverge (for example: see above the change to `terminalNodes`, the fact that R uses 1-indexing makes it pretty annoying to use the same C++ code). 

@edwardwliu On `terminalNodes` specifically, I am thinking we may want to remove the current implementation and replace it with a common `decision_path` function as is used in SK Learn. Then we can just maintain a single function for R and Python that will be able to retrieve the terminal nodes of predictions (and the entire path), in a format that users are more familiar with since it will match the SK Learn API. I'll plan to bring this up during our next sync to see if Jas has an objection.

**Comment by edwardwliu** [comment]
Sounds good, you can go ahead and merge this in so we can deprecate our usage of the fork. I agree on the `decision_path` suggestion. Specifically, adhering to an sklearn-like API and offloading as much logic to the shared C++ are good principles to follow.

**Comment by theo-s** [comment]
That sounds good, I will merge this in. Related to the `decision_path` discussion, medium term we should look at the SK Learn API and see what else we are missing, it seems like many functions could be added from there to standardize the API in both languages.

**Pull request merged**
