### PR TITLE
sklearn compatibility

### PR DESCRIPTION
**Pull request by petrovicboban**

### CODE REVIEW

**Comment by petrovicboban** [comment]
@edwardwliu can you figure out why test is failing here? I've tried to do it, but it goes deep into logic (categorical feature mapping).

**Comment by edwardwliu** [comment]
The issue was `find_match()` wasn't identifying matching values for different `np.int` and `np.float64` types. I added a cast, but it's possible this could be handled in a cleaner manner. The test appears to be passing now.

**Comment by petrovicboban** [comment]
@edwardwliu  thanks! I thought the issue was in calling function, because the test was failing when `arr_b` was numpy array. In all other tests, it was list.

**Comment by petrovicboban** [comment]
@edwardwliu 
it seems that `fit()` should not change parameters which are set during `__init__()`, and that's exactly what we do.
Here is test failure: https://github.com/forestry-labs/Rforestry/actions/runs/4774656551/jobs/8488479086

**Comment by edwardwliu** [comment]
@petrovicboban I see, let's only use the following parameters in `fit()` and remove them from `__init__()` if overlapping:
* `feature_weights`
* `deep_feature_weights`
* `observation_weights`
* `lin_feats`
* `monotonic_constraints`
* `groups`

**Comment by petrovicboban** [comment]
@edwardwliu it looks like we need to move these too:

```    
        if self.max_depth is None:
            self.max_depth = round(nrow / 2) + 1

        if self.interaction_depth is None:
            self.interaction_depth = self.max_depth

        if self.max_obs is None:
            self.max_obs = y.size
```

because they depend on argument of `fit()`

**Comment by petrovicboban** [comment]
@edwardwliu can you help on current test failure?

**Comment by edwardwliu** [comment]
@petrovicboban Both of these test cases should be passing be now. The estimator test was because we do not currently support a data type `scipy.sparse.csc_matrix`. In addition, it may be useful to parameterize [checks](https://stackoverflow.com/a/70879187) while I debug.

**Comment by petrovicboban** [comment]
@edwardwliu this looks good for now. It fails only on estimator's pickle check. Probably because `saved_forest_` attribute is expected during the process but is added only after call to `translate_tree`. I've tried several solutions, but failed.

After we solve that, I need to improve `__init__` parameters validation.

**Comment by petrovicboban** [comment]
> @petrovicboban Both of these test cases should be passing be now. The estimator test was because we do not currently support a data type `scipy.sparse.csc_matrix`. In addition, it may be useful to parameterize [checks](https://stackoverflow.com/a/70879187) while I debug.

It's passing with:
```
    def _more_tags(self):
        return {
            "_xfail_checks": {
                "check_estimators_pickle": "To be fixed later",
                "check_n_features_in": "To be fixed later",
                "check_estimators_nan_inf": "To be fixed later",
                "check_dtype_object": "To be fixed later",
            },
        }
```

**Comment by Ilia-Shutov** [comment]
New PR based on this one was created https://github.com/forestry-labs/Rforestry/pull/146

**Pull request closed without merging**
