### PR TITLE
Enforce basic style checks

### PR DESCRIPTION
**Pull request by petrovicboban**
This PR enforces (python) coding standards in the project. 
It's probably not in the end state, we'll tweak settings per need.

### CODE REVIEW

**Comment by edwardwliu** [comment]
Thanks for the clean-up Boban. To clarify, what's the updated workflow for triggering/checking the linting?

**Comment by petrovicboban** [comment]
@edwardwliu Checks are added to existing python pipeline, so it's all transparent to developers. Job which builds sdist will do all the checks.

**Comment by edwardwliu** [comment]
So developers are expected to lint within their own environment, create a draft PR that will run checks, then resolve any highlighted items after?

**Comment by petrovicboban** [comment]
Yes, like here https://github.com/forestry-labs/Rforestry/actions/runs/4681149799/jobs/8293367913?pr=93. This means that PR can't be merged with lint/style errors.

**Comment by edwardwliu** [comment]
Got it. I'm open to that workflow, but think we could potentially make this non-blocking at first in case it affects other development. Let's loop in @theo-s on this change.

**Comment by petrovicboban** [comment]
@theo-s @edwardwliu is this ok to merge?

**Comment by petrovicboban** [comment]
@theo-s @edwardwliu is this fine to merge?

**Comment by edwardwliu** [comment]
Yes I'm okay with merging this in, let's see if Theo agrees. 

This change does make linting a blocking check. I agree if not made blocking, developers will ignore it. However, pushing a PR then running checks is not efficient. I see two fixes that we discussed as a follow-on:

1. Allow devs to easily run the check locally (what's the best way to do this?)
2. Add style guidance or default IDE settings to the repo.

**Comment by petrovicboban** [comment]
@edwardwliu we can have a script in `tools` folder which would run the same checks as github actions, so developers can run it per need.

**Comment by petrovicboban** [comment]
We can also add `.vscode` to the repo, which would be very convenient for vscode users, but it doesn't cover other IDEs.

**Comment by petrovicboban** [comment]
@edwardwliu  can you review?

**Pull request merged**
