### PR TITLE
Fix Python Saving + Loading

### PR DESCRIPTION
**Pull request by theo-s**
Python saving loading is now working as expected across a number of hyper parameter settings. It may be brittle, so testing further before I make this a full PR.

Fixed name again.

### CODE REVIEW

**Comment by theo-s** [comment]
This has passed my further tests locally, it appears the errors are to do with the build. 

Will try to quash these, but it might be worth just merging in the changes to the C++/Python code.

**Comment by theo-s** [comment]
@petrovicboban I have a problem with my build when pushing (I can build and recompile the project easily locally, but it doesn't match the setup when it is run through the pipelines). 

It would be great to work out exactly what the difference is, I probably just need to clone master again and set it up. For now, since this fork only contains minor changes to two files (that have large logical implications), would you mind integrating the changes to these two files into master?

**Comment by petrovicboban** [comment]
The error happens because pipeline can't checkout specific commit of armadillo repo. I'll try to fix it.

**Review by edwardwliu — APPROVED** [review]

**Comment by edwardwliu** [comment]
Thanks! @theo-s Could you run the style checker above and merge in this PR?

**Comment by theo-s** [comment]
Thanks @petrovicboban for fixing this, I'll update the style checks and merge this in when the checks pass

**Pull request merged**
