### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by petrovicboban**

### CODE REVIEW

**Comment by petrovicboban** [comment]
@theo-s this may affect generation of github pages. Can you verify it?

**Comment by theo-s** [comment]
I think we should keep the Readme.Md outside of the R folder so that we can see this on the landing page from Github. 

I think we are okay removing `_pkgdown.yml` though.

**Comment by petrovicboban** [comment]
That `README.md` contains only R stuff. Maybe it's better to have a general `README.md` in the root of repo, which describes what this project tries to accomplish, and how, but leave detailed how-to `README.md`s with examples in wrappers folders (R/Python). `README.md` in subfolders are represented the same way as in the root of repository, and the main `README.md` should have links to subfolders `README.md`s.

**Comment by edwardwliu** [comment]
Good documentation will be important prior to the release of the Python package. Is this something that Sam could help with? In the meantime, I'm okay leaving the README in the root for now and updating actual content in a future change.

Regarding priorities, we're most interested in a release of the R package with custom sampling. I'll work to land the feature and @theo-s can you help with testing for any regressions across existing behavior in the R package? I can share a list of important feature interactions. If we have a build from source early next week, we can test it in an external pipeline and target an R release next week. 

In parallel, @petrovicboban could you take the lead on ensuring we're all set for a Python release from a build perspective (pinning dependencies etc.)? Possibly also set up a way to test outputs across R and Python versions. Afterwards, there are a number of "UX" items such as naming of the package and documentation that we all have to resolve. Let's aim to address those through next week and officially release the Python package the week after. I've updated the Kaban, let me know if anyone has other thoughts.

**Comment by theo-s** [comment]
Thanks for outlining this course of action, it sounds like the sampling procedure is of very high priority. Would it help if I allocated some cycles this weekend to help implement the feature? If you feel you have a good handle on it, then totally good to focus on testing next week.

On the tests for the outputs of the R and Python packages, I have some thoughts on how we can do this cleanly, maybe lets plan to discuss this @petrovicboban during the Rforestry sync next Monday?

Btw, one change induced by our new file structure is how users will have to install the R package from Github using an updated file path. They used to be able to do `devtools::install_github("forestry-labs/Rforestry")`, now they will need to add a path to the R folder. So we will have to change any instructions for installing the R package to reflect this change (or point them to install the version on CRAN). 

See: [https://github.com/forestry-labs/causalToolbox/issues/7](https://github.com/forestry-labs/causalToolbox/issues/7)

**Comment by edwardwliu** [comment]
Yes, help with implementing and testing the feature would be great! Moreso landing the feature and verifying no regressions in behavior across the R package. I'll push what I have by EOD today and we can collaborate to merge it in over the weekend.

Discussing the testing plan during our sync sounds good as well.

**Comment by JasjeetSekhon** [comment]
“ it sounds like the sampling procedure is of very high priority.”

Yes, thanks

**Pull request merged**
